# TODO ref https://github.com/scikit-learn/scikit-learn/blob/main/.github/workflows/publish_pypi.yml

name: Publish to Pypi
on:
  workflow_dispatch:
    inputs:
      pypi_repo:
        description: 'Repo to upload to (testpypi or pypi)'
        default: 'testpypi'
        required: true

jobs:
  publish:
    runs-on: debian-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade build twine
    - name: Build source and wheel distributions
      run: |
        python -m build
        python -m twine check --strict dist/*
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1.8.5
      with:
        repository_url: https://test.pypi.org/legacy/
      if: ${{ github.event.inputs.pypi_repo == 'testpypi' }}
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.5
      if: ${{ github.event.inputs.pypi_repo == 'pypi' }}
